# Official track programs for book entries 22–50 (sources: Wikipedia album
# pages; Discogs/Deezer for durations where Wikipedia lacked them).
# Continuous-video albums carry durations so the site can seek to each song.
TRACKS = {
  22: ["Big Iron", "Cool Water", "Billy the Kid", "A Hundred and Sixty Acres", "They're Hanging Me Tonight",
       "The Strawberry Roan", "El Paso", "In the Valley", "The Master's Call", "Running Gun",
       "The Little Green Valley", "Utah Carol"],
  24: ["Silver Dagger", "East Virginia", "Fare Thee Well (10,000 Miles)", "House of the Rising Sun", "All My Trials",
       "Wildwood Flower", "Donna Donna", "John Riley", "Rake and Rambling Boy", "Little Moses", "Mary Hamilton",
       "Henry Martin", "El Preso Número Nueve"],
  25: ["Make Me Know It", "Fever", "The Girl of My Best Friend", "I Will Be Home Again", "Dirty, Dirty Feeling",
       "Thrill of Your Love", "Soldier Boy", "Such a Night", "It Feels So Right", "Girl Next Door Went A-Walking",
       "Like a Baby", "Reconsider Baby"],
  26: ["The Retreat Song", "Suliram", "The Click Song", "Umhome", "Olilili", "Lakutshn, Ilanga", "Mbube",
       "The Naughty Little Flea", "Where Does It Lead?", "Nomeva", "House of the Rising Sun", "Saduva",
       "One More Dance", "Iya Guduza"],
  27: [("Made to Love", "2:05"), ("That's Just Too Much", "2:40"), ("Stick with Me Baby", "1:57"),
       ("Baby What You Want Me to Do", "2:20"), ("Sigh, Cry, Almost Die", "2:18"), ("Always It's You", "2:30"),
       ("Love Hurts", "2:23"), ("Lucille", "2:32"), ("So How Come (No One Loves Me)", "2:18"),
       ("Donna, Donna", "2:15"), ("A Change of Heart", "2:07"), ("Cathy's Clown", "2:25")],
  28: ["Back at the Chicken Shack", "When I Grow Too Old to Dream", "Minor Chant", "Messy Bessie"],
  29: [("I Got My Brand on You", "4:50"), ("I'm Your Hoochie Coochie Man", "2:57"), ("Baby, Please Don't Go", "3:04"),
       ("Soon Forgotten", "4:17"), ("Tiger in Your Tank", "4:32"), ("I Feel So Good", "3:01"),
       ("Got My Mojo Working", "4:27"), ("Got My Mojo Working, Part 2", "2:55"), ("Goodbye Newport Blues", "4:53")],
  30: ["Gloria's Step", "My Man's Gone Now", "Solar", "Alice in Wonderland", "All of You", "Jade Visions"],
  31: ["Bye Bye Love", "You Don't Know Me", "Half as Much", "I Love You So Much It Hurts",
       "Just a Little Lovin' (Will Go a Long Way)", "Born to Lose", "Worried Mind", "It Makes No Difference Now",
       "You Win Again", "Careless Love", "I Can't Stop Loving You", "Hey, Good Lookin'"],
  32: ["Green Onions", "Rinky Dink", "I Got a Woman", "Mo' Onions", "Twist and Shout", "Behave Yourself",
       "Stranger on the Shore", "Lonely Avenue", "One Who Really Loves You", "You Can't Sit Down",
       "A Woman, a Lover, a Friend", "Comin' Home Baby"],
  33: ["Desafinado", "Samba Dees Days", "O Pato", "Samba Triste", "Samba de Uma Nota Só", "É Luxo Só", "Bahia"],
  34: ["Introduction and Theme / Night Life", "Lonely Street", "The Wild Side of Life", "Sittin' and Thinkin'",
       "The Twenty-Fourth Hour", "A Girl in the Night", "Pride", "There's No Fool Like a Young Fool",
       "If She Could See Me Now", "Bright Lights and Blonde Haired Women", "Are You Sure", "Let Me Talk to You"],
  35: ["It Won't Be Long", "All I've Got to Do", "All My Loving", "Don't Bother Me", "Little Child",
       "Till There Was You", "Please Mr. Postman", "Roll Over Beethoven", "Hold Me Tight",
       "You Really Got a Hold on Me", "I Wanna Be Your Man", "Devil in Her Heart", "Not a Second Time",
       "Money (That's What I Want)"],
  36: ["Blowin' in the Wind", "Girl from the North Country", "Masters of War", "Down the Highway",
       "Bob Dylan's Blues", "A Hard Rain's a-Gonna Fall", "Don't Think Twice, It's All Right",
       "Bob Dylan's Dream", "Oxford Town", "Talkin' World War III Blues", "Corrina, Corrina",
       "Honey, Just Allow Me One More Chance", "I Shall Be Free"],
  37: ["White Christmas", "Frosty the Snowman", "The Bells of St. Mary's", "Santa Claus Is Coming to Town",
       "Sleigh Ride", "Marshmallow World", "I Saw Mommy Kissing Santa Claus", "Rudolph the Red-Nosed Reindeer",
       "Winter Wonderland", "Parade of the Wooden Soldiers", "Christmas (Baby Please Come Home)",
       "Here Comes Santa Claus", "Silent Night"],
  38: ["Feel It", "Chain Gang", "Cupid", "Medley: It's All Right / (I Love You) For Sentimental Reasons",
       "Twistin' the Night Away", "Somebody Have Mercy", "Bring It On Home to Me", "Nothing Can Change This Love",
       "Having a Party"],
  39: ["Track A – Solo Dancer", "Track B – Duet Solo Dancers", "Track C – Group Dancers",
       "Mode D / E / F – Trio and Group Dancers, Single Solos, Group and Solo Dance"],
  40: ["Introduction to James Brown and The Famous Flames", "I'll Go Crazy", "Try Me", "Think", "I Don't Mind",
       "Lost Someone", "Medley: Please, Please, Please / You've Got the Power / I Found Someone / …", "Night Train"],
  41: ["The Girl from Ipanema", "Doralice", "Para Machucar Meu Coração", "Desafinado",
       "Corcovado (Quiet Nights of Quiet Stars)", "Só Danço Samba", "O Grande Amor", "Vivo Sonhando"],
  42: ["A Hard Day's Night", "I Should Have Known Better", "If I Fell", "I'm Happy Just to Dance with You",
       "And I Love Her", "Tell Me Why", "Can't Buy Me Love", "Any Time at All", "I'll Cry Instead",
       "Things We Said Today", "When I Get Home", "You Can't Do That", "I'll Be Back"],
  43: ["Amsterdam", "Les Timides", "Le Dernier Repas", "Les Jardins du casino", "Les Vieux", "Les Toros",
       "Tango funèbre", "Le Plat Pays", "Les Bonbons", "Mathilde", "Les Bigotes", "Les Bourgeois", "Jef",
       "Au suivant", "Madeleine"],
  44: ["Goodbye Baby (Baby Goodbye)", "Cry to Me", "If You Need Me", "Hard Ain't It Hard",
       "Can't Nobody Love You", "Just Out of Reach (Of My Two Empty Arms)", "You're Good for Me",
       "He'll Have to Go", "Won't You Give Him (One More Chance)", "Someone to Love Me", "I Almost Lost My Mind",
       "Home in Your Heart"],
  45: ["Mama Said", "You Don't Own Me", "Do Re Mi", "When the Lovelight Starts Shining Through His Eyes",
       "My Colouring Book", "Mockingbird", "Twenty Four Hours from Tulsa", "Nothing", "Anyone Who Had a Heart",
       "Will You Love Me Tomorrow", "Wishin' and Hopin'", "Don't You Know"],
  46: ["Not Fade Away", "Route 66", "I Just Want to Make Love to You", "Honest I Do", "Now I've Got a Witness",
       "Little by Little", "I'm a King Bee", "Carol", "Tell Me", "Can I Get a Witness",
       "You Can Make It If You Try", "Walking the Dog"],
  47: [("I've Got a Tiger by the Tail", "2:10"), ("Trouble and Me", "1:53"), ("Let the Sad Times Roll On", "2:14"),
       ("Wham Bam", "2:00"), ("If You Fall Out of Love with Me", "2:15"), ("Fallin' for You", "1:58"),
       ("We're Gonna Let the Good Times Roll", "2:13"), ("The Band Keeps Playin' On", "3:01"),
       ("Streets of Laredo", "2:55"), ("Cryin' Time", "2:27"), ("A Maiden's Prayer", "2:32"), ("Memphis", "2:24")],
  48: ["Mean Woman Blues", "High School Confidential", "Money (That's What I Want)", "Matchbox",
       "What'd I Say, Part 1", "What'd I Say, Part 2", "Great Balls of Fire", "Good Golly, Miss Molly",
       "Lewis Boogie", "Your Cheatin' Heart", "Hound Dog", "Long Tall Sally", "Whole Lotta Shakin' Goin' On"],
  49: [("The Witch", "2:40"), ("Do You Love Me", "2:18"), ("Roll Over Beethoven", "2:49"), ("Boss Hoss", "2:24"),
       ("Dirty Robber", "2:02"), ("Have Love Will Travel", "2:40"), ("Psycho", "2:17"), ("Money", "2:00"),
       ("Walking the Dog", "2:45"), ("Night Time Is the Right Time", "2:58"), ("Strychnine", "2:13"),
       ("Good Golly Miss Molly", "2:08")],
  50: ["Subterranean Homesick Blues", "She Belongs to Me", "Maggie's Farm", "Love Minus Zero/No Limit",
       "Outlaw Blues", "On the Road Again", "Bob Dylan's 115th Dream", "Mr. Tambourine Man", "Gates of Eden",
       "It's Alright, Ma (I'm Only Bleeding)", "It's All Over Now, Baby Blue"],
}
